### ISSUE TITLE
website doesnt work when i ddos your servers

### ISSUE THREAD

**Issue by akulsharma1** [ArhanChaudhary/TimeWeb#16]
please figure out the issue 🙏

**Comment by ArhanChaudhary** [comment]
ur mom XDXDXXD

**Comment by ArhanChaudhary** [comment]
database had been configured with a connection age to avoid port exhaustion, ratelimiting will also be added in v1.8.0

**Comment by ArhanChaudhary** [comment]
2a55c3c
